# ruff: noqa
# mypy: ignore-errors
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import chat_pb2 as streaming_dot_v1_dot_chat__pb2

GRPC_GENERATED_VERSION = "1.83.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in streaming/v1/chat_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ChatServiceStub:
    """Bidirectional-streaming example. The client streams messages and the server
    streams a reply per message: the same text upper-cased, with the client's
    sequence number preserved. Regenerate the committed Python stubs with
    `python proto/regen_proto.py` (shared with the api_grpc overlay).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.stream_stream(
            "/streaming.v1.ChatService/Chat",
            request_serializer=streaming_dot_v1_dot_chat__pb2.ChatMessage.SerializeToString,
            response_deserializer=streaming_dot_v1_dot_chat__pb2.ChatMessage.FromString,
            _registered_method=True,
        )


class ChatServiceServicer:
    """Bidirectional-streaming example. The client streams messages and the server
    streams a reply per message: the same text upper-cased, with the client's
    sequence number preserved. Regenerate the committed Python stubs with
    `python proto/regen_proto.py` (shared with the api_grpc overlay).
    """

    def Chat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Chat": grpc.stream_stream_rpc_method_handler(
            servicer.Chat,
            request_deserializer=streaming_dot_v1_dot_chat__pb2.ChatMessage.FromString,
            response_serializer=streaming_dot_v1_dot_chat__pb2.ChatMessage.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "streaming.v1.ChatService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("streaming.v1.ChatService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ChatService:
    """Bidirectional-streaming example. The client streams messages and the server
    streams a reply per message: the same text upper-cased, with the client's
    sequence number preserved. Regenerate the committed Python stubs with
    `python proto/regen_proto.py` (shared with the api_grpc overlay).
    """

    @staticmethod
    def Chat(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/streaming.v1.ChatService/Chat",
            streaming_dot_v1_dot_chat__pb2.ChatMessage.SerializeToString,
            streaming_dot_v1_dot_chat__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
