# ruff: noqa
# mypy: ignore-errors
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming/v1/chat.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "streaming/v1/chat.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17streaming/v1/chat.proto\x12\x0cstreaming.v1"(\n\x0b\x43hatMessage\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t2O\n\x0b\x43hatService\x12@\n\x04\x43hat\x12\x19.streaming.v1.ChatMessage\x1a\x19.streaming.v1.ChatMessage(\x01\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "streaming.v1.chat_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CHATMESSAGE"]._serialized_start = 41
    _globals["_CHATMESSAGE"]._serialized_end = 81
    _globals["_CHATSERVICE"]._serialized_start = 83
    _globals["_CHATSERVICE"]._serialized_end = 162
# @@protoc_insertion_point(module_scope)
