# ruff: noqa
# mypy: ignore-errors
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import example_pb2 as example_dot_v1_dot_example__pb2

GRPC_GENERATED_VERSION = "1.83.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in example/v1/example_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ExampleServiceStub:
    """Example gRPC service: one unary method and one server-streaming method.
    Regenerate the committed Python stubs with `python proto/regen_proto.py`
    (pinned grpcio-tools + protobuf, see the script). CI runs it then
    `git diff --exit-code` so the committed stubs can never drift (D-009).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Greet = channel.unary_unary(
            "/example.v1.ExampleService/Greet",
            request_serializer=example_dot_v1_dot_example__pb2.GreetRequest.SerializeToString,
            response_deserializer=example_dot_v1_dot_example__pb2.GreetReply.FromString,
            _registered_method=True,
        )
        self.Ticks = channel.unary_stream(
            "/example.v1.ExampleService/Ticks",
            request_serializer=example_dot_v1_dot_example__pb2.TicksRequest.SerializeToString,
            response_deserializer=example_dot_v1_dot_example__pb2.Tick.FromString,
            _registered_method=True,
        )


class ExampleServiceServicer:
    """Example gRPC service: one unary method and one server-streaming method.
    Regenerate the committed Python stubs with `python proto/regen_proto.py`
    (pinned grpcio-tools + protobuf, see the script). CI runs it then
    `git diff --exit-code` so the committed stubs can never drift (D-009).
    """

    def Greet(self, request, context):
        """Unary: echo a greeting back to the caller."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Ticks(self, request, context):
        """Server streaming: emit `count` sequential ticks."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ExampleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Greet": grpc.unary_unary_rpc_method_handler(
            servicer.Greet,
            request_deserializer=example_dot_v1_dot_example__pb2.GreetRequest.FromString,
            response_serializer=example_dot_v1_dot_example__pb2.GreetReply.SerializeToString,
        ),
        "Ticks": grpc.unary_stream_rpc_method_handler(
            servicer.Ticks,
            request_deserializer=example_dot_v1_dot_example__pb2.TicksRequest.FromString,
            response_serializer=example_dot_v1_dot_example__pb2.Tick.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "example.v1.ExampleService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("example.v1.ExampleService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ExampleService:
    """Example gRPC service: one unary method and one server-streaming method.
    Regenerate the committed Python stubs with `python proto/regen_proto.py`
    (pinned grpcio-tools + protobuf, see the script). CI runs it then
    `git diff --exit-code` so the committed stubs can never drift (D-009).
    """

    @staticmethod
    def Greet(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/example.v1.ExampleService/Greet",
            example_dot_v1_dot_example__pb2.GreetRequest.SerializeToString,
            example_dot_v1_dot_example__pb2.GreetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Ticks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/example.v1.ExampleService/Ticks",
            example_dot_v1_dot_example__pb2.TicksRequest.SerializeToString,
            example_dot_v1_dot_example__pb2.Tick.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
