# ruff: noqa
# mypy: ignore-errors
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example/v1/example.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "example/v1/example.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18\x65xample/v1/example.proto\x12\nexample.v1"\x1c\n\x0cGreetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"\x1d\n\nGreetReply\x12\x0f\n\x07message\x18\x01 \x01(\t"\x1d\n\x0cTicksRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\r"\x15\n\x04Tick\x12\r\n\x05index\x18\x01 \x01(\r2\x82\x01\n\x0e\x45xampleService\x12\x39\n\x05Greet\x12\x18.example.v1.GreetRequest\x1a\x16.example.v1.GreetReply\x12\x35\n\x05Ticks\x12\x18.example.v1.TicksRequest\x1a\x10.example.v1.Tick0\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "example.v1.example_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GREETREQUEST"]._serialized_start = 40
    _globals["_GREETREQUEST"]._serialized_end = 68
    _globals["_GREETREPLY"]._serialized_start = 70
    _globals["_GREETREPLY"]._serialized_end = 99
    _globals["_TICKSREQUEST"]._serialized_start = 101
    _globals["_TICKSREQUEST"]._serialized_end = 130
    _globals["_TICK"]._serialized_start = 132
    _globals["_TICK"]._serialized_end = 153
    _globals["_EXAMPLESERVICE"]._serialized_start = 156
    _globals["_EXAMPLESERVICE"]._serialized_end = 286
# @@protoc_insertion_point(module_scope)
