#!/usr/bin/env python3
"""Derive ``copier.yml`` from ``registry.yaml``.

Interface: ``docs/registry-schema.md`` §6. Owner: Registry & Copier Architect.

``copier.yml`` is a pure, deterministic function of ``registry.yaml``: same input,
byte-identical output. No network, no randomness, stable key ordering. The file
is GENERATED; nobody edits it by hand. CI runs ``--check`` and fails on drift.

What it emits:
  * Copier settings: ``_subdirectory``, ``_templates_suffix``, ``_answers_file``,
    ``_min_copier_version``, ``_exclude`` (defaults + ``_fragments`` +
    ``_fragments/**`` + ``overlays``), ``_skip_if_exists`` (from
    ``meta.skip_if_exists``), ``_tasks`` (from top-level ``tasks`` plus any
    per-option ``tasks``), ``_migrations`` (from ``migrations``, omitted if empty).
  * one question per ``options`` entry, ordered by ``groups[group].order`` then by
    the order the option appears in ``registry.yaml``. Each carries ``type``,
    ``help`` (the ``prompt``, unless the option is computed), ``choices``,
    ``multiselect``, ``default`` (omitted when null), ``when`` (``false`` for a
    computed key, else the expression), and a compiled ``validator``.
  * ``validator`` blocks compiled from ``validation_rules`` (attached to a
    question by ``attach_to``), from a structured ``option.validator`` (regex),
    and from any per-option ``requires`` / ``conflicts`` whose expression is not
    already covered by an attached rule or by the option's own ``when``.

Usage:
    scripts/gen_copier_yml.py                 # write copier.yml
    scripts/gen_copier_yml.py --check         # exit 1 if copier.yml is stale
    scripts/gen_copier_yml.py --stdout        # print, do not write
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ModuleNotFoundError:  # pragma: no cover
    print("PyYAML is required: `uv sync` or `pip install pyyaml`", file=sys.stderr)
    raise SystemExit(2) from None

DRIFT_EXIT = 1
ERROR_EXIT = 2

# Copier's built-in _exclude defaults (docs: configuring a template). Defining
# _exclude in copier.yml REPLACES these, so we re-list them, then append ours.
COPIER_DEFAULT_EXCLUDES = (
    "copier.yaml",
    "copier.yml",
    "~*",
    "*.py[co]",
    "__pycache__",
    ".git",
    ".DS_Store",
    ".svn",
)
# Ours: fragment partials live at template/_fragments/, which renders to a
# root-level `_fragments/` in the destination after `_subdirectory` strips the
# prefix. ANCHOR the pattern with a leading slash: an unanchored bare name
# matches a directory of that name at ANY depth, which would also eat things
# like a rendered `tests/_fragments/`. `includes/` and `overlays/` sit OUTSIDE
# `_subdirectory` and are never generation candidates, so they get NO exclude
# entry - a bare `overlays` here silently drops the rendered `tests/overlays/`
# subtree (every overlay's proves-it-boots test).
EXTRA_EXCLUDES = ("/_fragments", "/_fragments/**")

HEADER = """\
# =============================================================================
# GENERATED by scripts/gen_copier_yml.py from registry.yaml. DO NOT EDIT.
#
# Regenerate:  python scripts/gen_copier_yml.py
# Check drift: python scripts/gen_copier_yml.py --check
#
# Every prompt here maps 1:1 to a registry key. Validation comes from
# registry.yaml `validation_rules` and per-option `requires`/`conflicts`.
# =============================================================================
"""


# --------------------------------------------------------------------------- #
# YAML scalar emission (hand-built for full byte control)
# --------------------------------------------------------------------------- #

_BARE_LABEL_OK = frozenset("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-")


def _dq(value: str) -> str:
    """Double-quoted YAML scalar."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return _dq(value)
    raise TypeError(f"unsupported scalar: {value!r}")


def _label(text: str) -> str:
    """A choices-map key: bare when simple, quoted otherwise."""
    if text and all(ch in _BARE_LABEL_OK for ch in text):
        return text
    return _dq(text)


# --------------------------------------------------------------------------- #
# expression helpers
# --------------------------------------------------------------------------- #


def _norm(expr: str) -> str:
    """Whitespace-insensitive form of an expression, for equality checks."""
    return "".join(expr.split())


# --------------------------------------------------------------------------- #
# validator compilation
# --------------------------------------------------------------------------- #


def _clause(condition: str, message: str) -> str:
    """One `{% if %}` paragraph for a `>-` folded validator block."""
    return f"{{% if {condition} %}}\n{message}\n{{% endif %}}"


def _validator_clauses(
    key: str, opt: dict[str, Any], rules_by_key: dict[str, list[dict[str, Any]]]
) -> list[str]:
    clauses: list[str] = []
    seen_norm: set[str] = set()

    # 1. structured regex validator (input shape)
    v = opt.get("validator")
    if isinstance(v, dict) and v.get("regex"):
        rx = v["regex"]
        msg = v.get("message", f"{key} does not match {rx}")
        clauses.append(_clause(f"not ({key} | regex_search('{rx}'))", msg))

    # 2. validation_rules attached to this key
    for rule in rules_by_key.get(key, []):
        applies = str(rule.get("applies_when", "true")).strip()
        expr = rule["expr"].strip()
        cond = (
            f"({applies}) and not ({expr})"
            if applies not in ("", "true", "True")
            else f"not ({expr})"
        )
        norm = _norm(cond)
        if norm in seen_norm:
            continue
        seen_norm.add(norm)
        clauses.append(_clause(cond, rule["message"]))

    # 3. per-option requires / conflicts, but ONLY when NO validation_rule attaches
    #    to this key. `validation_rules` is the canonical list (registry-schema
    #    §4); per-option requires/conflicts are the fallback for a key no rule
    #    covers (v0: only `embedding_vector_size`). This keeps the generated
    #    validator free of the near-duplicate clauses that the "restated"
    #    requires would otherwise produce.
    if key in rules_by_key:
        return clauses

    own_when = _norm(opt["when"]) if isinstance(opt.get("when"), str) else None
    is_bool = opt.get("type") == "bool"
    guard = f"{key} and " if is_bool else ""

    for req in opt.get("requires", []) or []:
        expr = req["expr"].strip()
        if _norm(expr) == own_when:
            continue
        cond = f"{guard}not ({expr})"
        if _norm(cond) in seen_norm:
            continue
        seen_norm.add(_norm(cond))
        clauses.append(_clause(cond, req["message"]))

    for conf in opt.get("conflicts", []) or []:
        expr = conf["expr"].strip()
        cond = f"{guard}({expr})"
        if _norm(cond) in seen_norm:
            continue
        seen_norm.add(_norm(cond))
        clauses.append(_clause(cond, conf["message"]))

    return clauses


# --------------------------------------------------------------------------- #
# blocks
# --------------------------------------------------------------------------- #


def _settings_block(reg: dict[str, Any]) -> list[str]:
    meta = reg.get("meta", {})
    out: list[str] = []
    out.append(f"_subdirectory: {meta.get('subdirectory', 'template')}")
    out.append("_templates_suffix: .jinja")
    out.append(f"_answers_file: {meta.get('answers_file', '.copier-answers.yml')}")
    out.append(f"_min_copier_version: {_dq(str(meta.get('copier_min_version', '9.18.2')))}")

    out.append("")
    out.append("_exclude:")
    for pat in (*COPIER_DEFAULT_EXCLUDES, *EXTRA_EXCLUDES):
        out.append(f"  - {_dq(pat)}")

    skip = meta.get("skip_if_exists") or []
    if skip:
        out.append("")
        out.append("_skip_if_exists:")
        for pat in skip:
            out.append(f"  - {_dq(str(pat))}")

    tasks = _collect_tasks(reg)
    if tasks:
        out.append("")
        out.append("# List-form argv, no shell (D-012).")
        out.append("_tasks:")
        for task in tasks:
            cmd = ", ".join(_dq(str(a)) for a in task["command"])
            out.append(f"  - command: [{cmd}]")
            if task.get("when"):
                out.append(f"    when: {_dq(task['when'])}")

    migrations = reg.get("migrations") or []
    if migrations:
        out.append("")
        out.append("_migrations:")
        for mig in migrations:
            out.append(f"  - {yaml.safe_dump(mig, default_flow_style=True).strip()}")

    return out


def _collect_tasks(reg: dict[str, Any]) -> list[dict[str, Any]]:
    """Base tasks first, then per-option tasks with the gate folded into `when`."""
    tasks: list[dict[str, Any]] = []
    for task in reg.get("tasks", []) or []:
        tasks.append({"command": task["command"], "when": task.get("when")})

    for key, opt in reg.get("options", {}).items():
        gate = opt.get("gate") or (key if opt.get("type") == "bool" else None)
        for task in opt.get("tasks", []) or []:
            when = task.get("when")
            if gate and when:
                folded = f"{{{{ ({gate}) and ({_strip_jinja(when)}) }}}}"
            elif gate:
                folded = f"{{{{ {gate} }}}}"
            else:
                folded = when
            tasks.append({"command": task["command"], "when": folded})
    return tasks


def _strip_jinja(expr: str) -> str:
    e = expr.strip()
    if e.startswith("{{") and e.endswith("}}"):
        return e[2:-2].strip()
    return e


def _question_block(
    key: str, opt: dict[str, Any], rules_by_key: dict[str, list[dict[str, Any]]]
) -> list[str]:
    out: list[str] = [f"{key}:"]
    out.append(f"  type: {opt.get('type', 'str')}")

    when = opt.get("when")
    computed = when is False
    prompt = opt.get("prompt")
    if not computed and prompt and prompt != "computed":
        out.append(f"  help: {_dq(prompt)}")

    choices = opt.get("choices")
    if choices is not None:
        out.append("  choices:")
        if isinstance(choices, dict):
            for lbl, val in choices.items():
                out.append(f"    {_label(str(lbl))}: {val}")
        else:
            for val in choices:
                out.append(f"    - {val}")

    if opt.get("multiselect"):
        out.append("  multiselect: true")

    default = opt.get("default")
    if default is not None:
        if isinstance(default, list):
            out.append(
                "  default: []"
                if not default
                else f"  default: {yaml.safe_dump(default, default_flow_style=True).strip()}"
            )
        elif isinstance(default, dict):
            out.append(
                "  default: {}"
                if not default
                else f"  default: {yaml.safe_dump(default, default_flow_style=True).strip()}"
            )
        else:
            out.append(f"  default: {_scalar(default)}")

    if computed:
        out.append("  when: false")
    elif isinstance(when, str):
        out.append(f"  when: {_dq(when)}")

    clauses = _validator_clauses(key, opt, rules_by_key)
    if clauses:
        out.append("  validator: >-")
        for i, clause in enumerate(clauses):
            if i:
                out.append("")
            for line in clause.splitlines():
                out.append(f"    {line}")

    return out


# --------------------------------------------------------------------------- #
# top level
# --------------------------------------------------------------------------- #


def build_copier_yml(registry_path: Path) -> str:
    with registry_path.open() as fh:
        reg = yaml.safe_load(fh)
    if not isinstance(reg, dict):
        raise ValueError("registry.yaml top level must be a mapping")

    groups: dict[str, dict[str, Any]] = reg.get("groups", {})
    options: dict[str, dict[str, Any]] = reg.get("options", {})

    rules_by_key: dict[str, list[dict[str, Any]]] = {}
    for rule in reg.get("validation_rules", []) or []:
        # `scope: services_config` rules are structural predicates over the
        # services_config map, checked by validate_registry.validate_services_config
        # in the CLI (D-036). They are NOT Jinja booleans and never become Copier
        # validators, regardless of their `attach_to` (kept for discoverability).
        if rule.get("scope", "copier") != "copier":
            continue
        for target in rule.get("attach_to", []) or []:
            rules_by_key.setdefault(target, []).append(rule)

    order: list[tuple[int, int, str]] = []
    for idx, key in enumerate(options):
        grp = options[key].get("group", "base")
        grp_order = groups.get(grp, {}).get("order", 999)
        order.append((grp_order, idx, key))
    order.sort()

    parts: list[str] = [HEADER.rstrip("\n"), ""]
    parts.extend(_settings_block(reg))
    parts.append("")

    last_group: str | None = None
    for _grp_order, _idx, key in order:
        grp = options[key].get("group", "base")
        if grp != last_group:
            title = groups.get(grp, {}).get("title", grp)
            parts.append(f"# ---- {grp}: {title} " + "-" * max(3, 60 - len(grp) - len(title)))
            last_group = grp
        parts.extend(_question_block(key, options[key], rules_by_key))
        parts.append("")

    text = "\n".join(parts).rstrip("\n") + "\n"
    return text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("registry", nargs="?", default="registry.yaml", type=Path)
    parser.add_argument("--check", action="store_true", help="exit 1 if copier.yml is stale")
    parser.add_argument("--stdout", action="store_true", help="print instead of writing")
    parser.add_argument(
        "--allow-missing", action="store_true", help="(compat) no-op now that the script is real"
    )
    parser.add_argument("--output", type=Path, default=Path("copier.yml"))
    args = parser.parse_args(argv)

    if not args.registry.exists():
        print(f"[gen_copier_yml] not found: {args.registry}", file=sys.stderr)
        return ERROR_EXIT

    try:
        rendered = build_copier_yml(args.registry)
    except (yaml.YAMLError, ValueError, KeyError, TypeError) as exc:
        print(f"[gen_copier_yml] {type(exc).__name__}: {exc}", file=sys.stderr)
        return ERROR_EXIT

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    if args.check:
        current = args.output.read_text() if args.output.exists() else ""
        if current != rendered:
            print(
                f"[gen_copier_yml] {args.output} is out of sync with {args.registry}. "
                "Run: python scripts/gen_copier_yml.py",
                file=sys.stderr,
            )
            return DRIFT_EXIT
        print(f"[gen_copier_yml] {args.output} is in sync")
        return 0

    args.output.write_text(rendered)
    print(f"[gen_copier_yml] wrote {args.output} ({rendered.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
